<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="8" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-13T12:19:19 IST" name="ProviderPlatformSuite" finished-at="2025-06-13T12:19:49 IST" duration-ms="30107">
    <groups>
    </groups>
    <test started-at="2025-06-13T12:19:19 IST" name="AllTests" finished-at="2025-06-13T12:19:49 IST" duration-ms="30107">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="BrowserMethod()[pri:0, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:19 IST" name="BrowserMethod" finished-at="2025-06-13T12:19:21 IST" duration-ms="1825" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserMethod -->
        <test-method signature="logintest()[pri:1, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:21 IST" name="logintest" description=" ATC-001, Login with valid credentials" finished-at="2025-06-13T12:19:22 IST" duration-ms="1188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method signature="loginWithInvalidCredentials()[pri:2, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:23 IST" name="loginWithInvalidCredentials" description=" ATC-002, Login with Invalid credentials" finished-at="2025-06-13T12:19:24 IST" duration-ms="1011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentials -->
        <test-method signature="loginWithBlankUsername()[pri:3, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:24 IST" name="loginWithBlankUsername" description="ATC-003, Login without username" finished-at="2025-06-13T12:19:25 IST" duration-ms="1364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithBlankUsername -->
        <test-method signature="loginWithBlankPassword()[pri:4, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:25 IST" name="loginWithBlankPassword" description="ATC-004, Login without password" finished-at="2025-06-13T12:19:27 IST" duration-ms="1915" status="FAIL">
          <exception class="org.openqa.selenium.NoAlertPresentException">
            <message>
              <![CDATA[no such alert
  (Session info: chrome=137.0.7151.69)
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [771f8e10dd9a77205d2d0f474518b2b2, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 137.0.7151.69, chrome: {chromedriverVersion: 137.0.7151.70 (dfa4dc56b2ab..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64235}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64235/devtoo..., se:cdpVersion: 137.0.7151.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 771f8e10dd9a77205d2d0f474518b2b2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoAlertPresentException: no such alert
  (Session info: chrome=137.0.7151.69)
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [771f8e10dd9a77205d2d0f474518b2b2, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 137.0.7151.69, chrome: {chromedriverVersion: 137.0.7151.70 (dfa4dc56b2ab..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64235}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64235/devtoo..., se:cdpVersion: 137.0.7151.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 771f8e10dd9a77205d2d0f474518b2b2
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1194)
at tests.LoginTest.loginWithBlankPassword(LoginTest.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoAlertPresentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithBlankPassword -->
        <test-method signature="loginWithBlankUsernameAndPassword()[pri:5, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:27 IST" name="loginWithBlankUsernameAndPassword" description="ATC-005, Login with blank username and password" finished-at="2025-06-13T12:19:28 IST" duration-ms="1138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithBlankUsernameAndPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@9d157ff]" started-at="2025-06-13T12:19:28 IST" name="tearDown" finished-at="2025-06-13T12:19:29 IST" duration-ms="935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.patientForm">
        <test-method is-config="true" signature="BrowserMethod()[pri:0, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:29 IST" name="BrowserMethod" finished-at="2025-06-13T12:19:31 IST" duration-ms="2144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserMethod -->
        <test-method is-config="true" signature="runLogin()[pri:0, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:31 IST" name="runLogin" finished-at="2025-06-13T12:19:33 IST" duration-ms="1410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runLogin -->
        <test-method signature="addPatient()[pri:6, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:33 IST" name="addPatient" description="ATC-006, Fill all the fields with valid data" finished-at="2025-06-13T12:19:37 IST" duration-ms="4292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPatient -->
        <test-method signature="validateTableEntry()[pri:7, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:37 IST" name="validateTableEntry" description="ATC-007, When submit the form, Table should increased by one" finished-at="2025-06-13T12:19:41 IST" duration-ms="3841" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTableEntry -->
        <test-method signature="clickSubmit()[pri:8, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:41 IST" name="clickSubmit" description="ATC-008, Leave all the fields empty and click submit" finished-at="2025-06-13T12:19:41 IST" duration-ms="332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickSubmit -->
        <test-method signature="invalidDOB()[pri:9, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:41 IST" name="invalidDOB" description="ATC-009,Enter Invalid DOB formate" finished-at="2025-06-13T12:19:43 IST" duration-ms="1581" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[entry not appear in table expected [4] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: entry not appear in table expected [4] but found [5]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at tests.patientForm.invalidDOB(patientForm.java:101)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidDOB -->
        <test-method signature="testFutureDOB()[pri:10, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:43 IST" name="testFutureDOB" description="ATC-010, Enter future DOB" finished-at="2025-06-13T12:19:44 IST" duration-ms="1562" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at tests.patientForm.testFutureDOB(patientForm.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFutureDOB -->
        <test-method signature="testSpecialCharInMRN()[pri:11, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:44 IST" name="testSpecialCharInMRN" description="ATC-011, Special characters in MRN" finished-at="2025-06-13T12:19:46 IST" duration-ms="1582" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[entry not appear in table expected [6] but found [7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: entry not appear in table expected [6] but found [7]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at tests.patientForm.testSpecialCharInMRN(patientForm.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSpecialCharInMRN -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.patientForm@6e57e95e]" started-at="2025-06-13T12:19:46 IST" name="tearDown" finished-at="2025-06-13T12:19:46 IST" duration-ms="302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.patientForm -->
      <class name="tests.LogoutTest">
        <test-method is-config="true" signature="BrowserMethod()[pri:0, instance:tests.LogoutTest@62f87c44]" started-at="2025-06-13T12:19:46 IST" name="BrowserMethod" finished-at="2025-06-13T12:19:48 IST" duration-ms="1657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserMethod -->
        <test-method signature="testSpecialCharInMRN()[pri:12, instance:tests.LogoutTest@62f87c44]" started-at="2025-06-13T12:19:48 IST" name="testSpecialCharInMRN" description="ATC-012, Verify successful logout" finished-at="2025-06-13T12:19:49 IST" duration-ms="1312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSpecialCharInMRN -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LogoutTest@62f87c44]" started-at="2025-06-13T12:19:49 IST" name="tearDown" finished-at="2025-06-13T12:19:49 IST" duration-ms="375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LogoutTest -->
    </test> <!-- AllTests -->
  </suite> <!-- ProviderPlatformSuite -->
</testng-results>
